// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Js_option = require("@rescript/runtime/lib/js/Js_option.js");
let Stdlib_JsExn = require("@rescript/runtime/lib/js/Stdlib_JsExn.js");
let Primitive_exceptions = require("@rescript/runtime/lib/js/Primitive_exceptions.js");
let Json_Decode$JsonCombinators = require("./Json_Decode.js");

let ParseError = /* @__PURE__ */Primitive_exceptions.create("Json-JsonCombinators.ParseError");

function parse(str) {
  try {
    return {
      TAG: "Ok",
      _0: JSON.parse(str)
    };
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    if (exn.RE_EXN_ID === "JsExn") {
      return {
        TAG: "Error",
        _0: Js_option.getWithDefault("Unknown error", Stdlib_JsExn.message(exn._1))
      };
    }
    throw exn;
  }
}

function parseExn(str) {
  try {
    return JSON.parse(str);
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    if (exn.RE_EXN_ID === "JsExn") {
      throw {
        RE_EXN_ID: ParseError,
        _1: Js_option.getWithDefault("Unknown error", Stdlib_JsExn.message(exn._1)),
        Error: new Error()
      };
    }
    throw exn;
  }
}

let Encode;

let Decode;

let decode = Json_Decode$JsonCombinators.decode;

exports.Encode = Encode;
exports.Decode = Decode;
exports.ParseError = ParseError;
exports.decode = decode;
exports.parse = parse;
exports.parseExn = parseExn;
/* Stdlib_JsExn Not a pure module */
