// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Stdlib_List from "@rescript/runtime/lib/es6/Stdlib_List.js";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function array(encode) {
  return arr => arr.map(x => encode(x));
}

function list(encode) {
  return l => {
    if (l === 0) {
      return [];
    }
    let arr = Stdlib_Array.make(Stdlib_List.length(l), encode(l.hd));
    let _i = 1;
    let _l = l.tl;
    while (true) {
      let l$1 = _l;
      let i = _i;
      if (l$1 === 0) {
        return arr;
      }
      arr[i] = encode(l$1.hd);
      _l = l$1.tl;
      _i = i + 1 | 0;
      continue;
    };
  };
}

let object = Js_dict.fromArray;

function option(encode) {
  return opt => {
    if (opt !== undefined) {
      return encode(Primitive_option.valFromOption(opt));
    } else {
      return null;
    }
  };
}

function withDefault($$default, encode, opt) {
  if (opt !== undefined) {
    return encode(Primitive_option.valFromOption(opt));
  } else {
    return $$default;
  }
}

function date(date$1) {
  return date$1.toJSON();
}

function pair(encodeA, encodeB, param) {
  return [
    encodeA(param[0]),
    encodeB(param[1])
  ];
}

function tuple2(encodeA, encodeB, param) {
  return [
    encodeA(param[0]),
    encodeB(param[1])
  ];
}

function tuple3(encodeA, encodeB, encodeC, param) {
  return [
    encodeA(param[0]),
    encodeB(param[1]),
    encodeC(param[2])
  ];
}

function tuple4(encodeA, encodeB, encodeC, encodeD, param) {
  return [
    encodeA(param[0]),
    encodeB(param[1]),
    encodeC(param[2]),
    encodeD(param[3])
  ];
}

function dict(encode, dict$1) {
  return Js_dict.map(v => encode(v), dict$1);
}

let Unsafe = {};

export {
  array,
  list,
  object,
  option,
  withDefault,
  date,
  pair,
  tuple2,
  tuple3,
  tuple4,
  dict,
  Unsafe,
}
/* No side effect */
